#!/usr/bin/bash

# # Example usage
# echo "=== FIGLET CENTER ==="
# align_output "$figftemp" "$term_width" center
#
# echo "=== LOGO RIGHT ==="
# align_output "$figftemp" "$term_width" right
#
# echo "=== FIGLET LEFT ==="
# align_output "$logotemp" "$term_width" left
# [==================(START)===================]
user="$(mktemp)"
figftemp="$(mktemp)"
logotemp="$(mktemp)"
term_width=$(stty size | cut -d ' ' -f 2)
version="$(mktemp)"
PUT() { echo -en "\033[${1};${2}H"; }
DRAW() {
  echo -en "\033%"
  echo -en "\033(0"
}
WRITE() { echo -en "\033(B"; }
HIDECURSOR() { echo -en "\033[?25l"; }
NORM() { echo -en "\033[?12l\033[?25h"; }

base64 -d >"$logotemp" <<'EOF'
G1s0OW0gICAgICAgICAgICAgICAgG1swbQobWzQ5bSAgICAbWzM4OzI7MDs0MDsxMTNt4paEG1sz
ODsyOzA7NDk7MTM2beKWhBtbMzg7MjswOzc1OzIxMDs0ODsyOzA7NDc7MTM0beKWhBtbMzg7Mjsw
OzM0Ozk2OzQ4OzI7MDs3NjsyMTRt4paMG1szODsyOzA7NjA7MTY5OzQ5beKWhBtbMzg7MjswOzg1
OzI0MDs0OW3ilowbWzM4OzI7MDszNDs5NDs0ODsyOzA7NzE7MjAwbeKWmBtbMzg7MjswOzQ1OzEy
Njs0OW3iloQgICAgG1swbQobWzQ5bSAgG1szODsyOzA7Mzc7MTA0beKWhBtbMzg7MjswOzYyOzE3
Nm3iloQbWzM4OzI7Njs4MzsyMjQ7NDg7MjsyMjE7MjI5OzIzOG3ilowbWzM4OzI7MTY5OzIxNDsy
MTY7NDg7MjsyMzM7MjM3OzI0NG3ilpYbWzM4OzI7MjU1OzI1NTsyNTU7NDg7MjsyMjI7MjI4OzIz
OW3iloTiloTiloTiloTiloQbWzM4OzI7MjM3OzI0MDsyNDY7NDg7Mjs3NDsxMTU7MTkzbeKWjBtb
Mzg7MjswOzc5OzIyMTs0OW3ilowbWzM4OzI7MDs0MzsxMjA7NDlt4paEICAbWzBtChtbNDltICAb
WzM4OzI7MDsyNDs2OTs0OW3iloQbWzM4OzI7MDszMzs5Mzs0ODsyOzA7NTg7MTYzbeKWjBtbMzg7
Mjs4OzgzOzIxNzs0ODsyOzIxNzsyMzY7MjM3beKWjBtbMzg7Mjs1NjsxODU7MTkyOzQ4OzI7MjU1
OzI1NTsyNTVt4paMG1szODsyOzI0MzsyNDU7MjQ5OzQ4OzI7NjQ7MTA3OzE5NG3ilpgbWzM4OzI7
MzQ7OTI7MTk2OzQ4OzI7MjM0OzIzODsyNDVt4paWG1szODsyOzg7ODM7MjE3OzQ4OzI7OTk7MTMy
OzE5MW3ilpYbWzM4OzI7NjY7MTEwOzE5Mzs0ODsyOzE3MDsxODY7MjE3beKWhBtbMzg7MjsxNDg7
MTY5OzIwOTs0ODsyOzI1NTsyNTU7MjU1beKWjBtbMzg7MjsyNTU7MjU1OzI1NTs0ODsyOzkyOzEy
ODsxOTRt4paMG1szODsyOzA7ODI7MjMxOzQ5beKWjBtbMzg7MjswOzI4OzgwOzQ5beKWhBtbNDlt
ICAbWzBtChtbNDltICAbWzM4OzI7MDs2OzE2OzQ4OzI7MDs0OTsxMzlt4paMG1szODsyOzA7NTI7
MTQ0OzQ4OzI7MDs2ODsxOTJt4paMG1szODsyOzg7ODM7MjE3OzQ4OzI7MjE3OzIzNjsyMzdt4paM
G1szODsyOzU2OzE4NTsxOTI7NDg7MjsyMjc7MjMyOzI0MW3ilowbWzM4OzI7MjU1OzI1NTsyNTU7
NDg7MjsxNTA7MTcwOzIxMG3iloQbWzQ4OzI7MTMzOzE1ODsyMDRt4paEG1szODsyOzgxOzEyMTsx
OTM7NDg7MjsyNTU7MjU1OzI1NW3ilpgbWzM4OzI7MTQyOzE2NTsyMDdt4padG1szODsyOzE1NDsx
NzQ7MjExbeKWmBtbMzg7MjsyNTU7MjU1OzI1NTs0ODsyOzkyOzEyODsxOTRt4paMG1szODsyOzA7
ODU7MjM4OzQ4OzI7MDs1MjsxNDRt4paMG1szODsyOzA7NTI7MTQ0OzQ5beKWjBtbNDltICAbWzBt
ChtbNDltICAgG1szODsyOzA7MzA7ODVt4paAG1szODsyOzIzOTsyNDc7MjQ3OzQ4OzI7MjI7ODQ7
MjA3beKWnRtbMzg7Mjs1NjsxMDU7MTkyOzQ4OzI7MTA3OzE5MzsxOTht4paEG1s0ODsyOzEzOTsy
MDI7MjA1beKWhOKWhOKWhOKWhBtbNDg7MjsyMjk7MjQxOzI0Mm3iloQbWzM4OzI7MjU1OzI1NTsy
NTU7NDg7Mjs2MTsxMDU7MTk5beKWmBtbMzg7MjswOzc5OzIyMDs0OW3ilpgbWzQ5bSAbWzQ5bSAg
G1swbQobWzQ5bSAgICAgG1szODsyOzA7ODg7MjQ4OzQ5beKWnRtbMzg7MjswOzM5OzExMDs0OW3i
loAbWzM4OzI7MDs0NDsxMjU7NDlt4paAG1szODsyOzA7ODA7MjI1OzQ5beKWmBtbMzg7MjswOzkx
OzI1NTs0OW3ilp0bWzQ5bSAbWzQ5bSAbWzQ5bSAgICAbWzBtChtbNDltICAgICAgICAgICAgICAg
IBtbMG0K
EOF
base64 -d >"$figftemp" <<'EOF'
G1szODsyOzIzNzsxMjk7MTdt4paAG1szOW0bWzM4OzI7MjM5OzEyNTsxOW3ilogbWzM5bRtbMzg7
MjsyNDE7MTIxOzIxbeKWgBtbMzltG1szODsyOzI0MzsxMTc7MjNt4oCBG1szOW0bWzM4OzI7MjQ0
OzExMjsyNm3iloQbWzM5bRtbMzg7MjsyNDY7MTA4OzI4beKWhBtbMzltG1szODsyOzI0NzsxMDQ7
MzFt4oCBG1szOW0bWzM4OzI7MjQ5OzEwMDszNG3ilogbWzM5bRtbMzg7MjsyNTA7OTY7MzdtIBtb
MzltG1szODsyOzI1MTs5Mjs0MG3ilogbWzM5bRtbMzg7MjsyNTI7ODg7NDNt4oCBG1szOW0bWzM4
OzI7MjUzOzg0OzQ2beKWiBtbMzltG1szODsyOzI1Mzs4MDs1MG3iloAbWzM5bRtbMzg7MjsyNTQ7
NzY7NTNt4paAG1szOW0bWzM4OzI7MjU0OzcyOzU2beKAgRtbMzltG1szODsyOzI1NDs2ODs2MG3i
loQbWzM5bRtbMzg7MjsyNTQ7NjQ7NjRt4paAG1szOW0bWzM4OzI7MjU0OzYxOzY3beKWiBtbMzlt
G1szODsyOzI1NDs1Nzs3MW3igIEbWzM5bRtbMzg7MjsyNTQ7NTQ7NzVt4paIG1szOW0bWzM4OzI7
MjUzOzUwOzc5beKWgBtbMzltG1szODsyOzI1Mzs0Nzs4M23iloQbWzM5bRtbMzg7MjsyNTI7NDQ7
ODdt4oCBG1szOW0bWzM4OzI7MjUxOzQxOzkxbeKWiBtbMzltG1szODsyOzI1MDszODs5NW3iloAb
WzM5bRtbMzg7MjsyNDk7MzU7OTlt4paAG1szOW0bWzM4OzI7MjQ4OzMyOzEwM23igIEbWzM5bRtb
Mzg7MjsyNDY7Mjk7MTA3beKWiBtbMzltG1szODsyOzI0NTsyNjsxMTFt4paAG1szOW0bWzM4OzI7
MjQzOzI0OzExNm3ilogbWzM5bRtbMzg7MjsyNDE7MjI7MTIwbeKAgRtbMzltG1szODsyOzIzOTsx
OTsxMjRtG1szOW0KG1szODsyOzI0MzsxMTc7MjNtIBtbMzltG1szODsyOzI0NDsxMTI7MjZt4paI
G1szOW0bWzM4OzI7MjQ2OzEwODsyOG3igIEbWzM5bRtbMzg7MjsyNDc7MTA0OzMxbeKAgRtbMzlt
G1szODsyOzI0OTsxMDA7MzRt4oCBG1szOW0bWzM4OzI7MjUwOzk2OzM3beKAgRtbMzltG1szODsy
OzI1MTs5Mjs0MG3igIEbWzM5bRtbMzg7MjsyNTI7ODg7NDNt4paIG1szOW0bWzM4OzI7MjUzOzg0
OzQ2beKWgBtbMzltG1szODsyOzI1Mzs4MDs1MG3ilogbWzM5bRtbMzg7MjsyNTQ7NzY7NTNt4oCB
G1szOW0bWzM4OzI7MjU0OzcyOzU2beKWiBtbMzltG1szODsyOzI1NDs2ODs2MG3ilogbWzM5bRtb
Mzg7MjsyNTQ7NjQ7NjRt4paEG1szOW0bWzM4OzI7MjU0OzYxOzY3beKAgRtbMzltG1szODsyOzI1
NDs1Nzs3MW3ilogbWzM5bRtbMzg7MjsyNTQ7NTQ7NzVt4paAG1szOW0bWzM4OzI7MjUzOzUwOzc5
beKWiBtbMzltG1szODsyOzI1Mzs0Nzs4M23igIEbWzM5bRtbMzg7MjsyNTI7NDQ7ODdt4paIG1sz
OW0bWzM4OzI7MjUxOzQxOzkxbeKWhBtbMzltG1szODsyOzI1MDszODs5NW3iloAbWzM5bRtbMzg7
MjsyNDk7MzU7OTlt4oCBG1szOW0bWzM4OzI7MjQ4OzMyOzEwM23ilogbWzM5bRtbMzg7MjsyNDY7
Mjk7MTA3beKWiBtbMzltG1szODsyOzI0NTsyNjsxMTFt4paEG1szOW0bWzM4OzI7MjQzOzI0OzEx
Nm3igIEbWzM5bRtbMzg7MjsyNDE7MjI7MTIwbeKWiBtbMzltG1szODsyOzIzOTsxOTsxMjRt4paA
G1szOW0bWzM4OzI7MjM3OzE3OzEyOG3iloQbWzM5bRtbMzg7MjsyMzU7MTU7MTMybeKAgRtbMzlt
G1szODsyOzIzMzsxMzsxMzdtG1szOW0K
EOF
echo -e "\e[32mSetup Script \e[33m3.0\e[0m" > "$version"
# ${1}=figlet, ${2}=logo
banner() {
  HIDECURSOR
  clear
  echo -e "\033[35;1m"
  PUT 0 0
  echo "┌$(seq -s─ $((term_width - 1)) | tr -d '[:digit:]')┐"
  for ((i = 1; i <= 8; i++)); do
    echo "│$(seq -s\  $((term_width - 1)) | tr -d '[:digit:]')│"
  done
  echo "└$(seq -s─ $((term_width - 1)) | tr -d '[:digit:]')┘"
  PUT 5 0
  # print_prefixed_file "${1}"
  if (( term_width > 59 )); then
    align_output "$figftemp" "$term_width" right
    PUT 2 0
    # print_center_file "${2}"
    align_output "$logotemp" "$term_width" left
    PUT 9 0
    align_output "$version" "$term_width" lvers
  else
    align_output "$figftemp" "$term_width" center
    PUT 9 0
    align_output "$version" "$term_width" lvers
  fi
  PUT 1 0
  echo -e "\033[35;1m"
  for ((i = 1; i <= 8; i++)); do
    echo "│"
  done
  PUT 10 0
  echo
  NORM
}

align_output() {
  local file="$1"   # content file
  local canvas="$2" # terminal width (stty size)
  local align="$3"  # 0=left, 1=center, 2=right

  # Internal ANSI stripper
  strip_ansi() { sed "s/\x1B\[[0-9;]*[mGK]//g"; }

  while IFS= read -r line; do
    local clean_line=$(echo "$line" | strip_ansi)
    local line_length=${#clean_line}
    local pad=0

    case "$align" in
      center) pad=$(((canvas - line_length) / 2)) ;; # center
      right) pad=$((canvas - line_length - 7)) ;;    # right
      lvers) pad=$((canvas - line_length - 3)) ;;
      *) pad=3 ;; # left
    esac

    [ $pad -lt 0 ] && pad=0
    printf "%*s%s\n" "$pad" "" "$line"
  done <"$file"
}
